Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DB.Aplication.contracts;
using DB.Aplication.contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {

        private readonly IArticleCategoryApplication articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            this.articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
        }
        public RedirectToPageResult OnPost(CreateArticleCategory command)
        {
            articleCategoryApplication.Create(command);
            return RedirectToPage("./index");
        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DB.Aplication.contracts;
using DB.Aplication.contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty] public RenameArticleCategory ArticleCategory { set; get; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            ArticleCategory = _articleCategoryApplication.Get(id);
        }
        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Rename(ArticleCategory);
            return RedirectToPage("/articlecategorymanagement/index");
        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Index.cshtml.cs
using System.Collections.Generic;
using DB.Aplication.contracts;
using DB.Aplication.contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class IndexModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArtileCategories { get; set; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArtileCategories = _articleCategoryApplication.List();
        }
        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./index");
        }
        public RedirectToPageResult OnPost(long id)
        {
            _articleCategoryApplication.Active(id);
            return RedirectToPage("/articlecategorymanagement/index");
        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MB.Presentation.MVCCore2.Areas.Admin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MB.Presentation.MVCCore2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

       

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MB.Presentation.MVCCore2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MB.Presentation.MVCCore2.Pages
{
    public class PrivacyModel : PageModel
    {
      

        

        public void OnGet()
        {
        }
    }
}

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Create.cshtml
@page
@model MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement.CreateModel
@{
}


<div class="card">
    <div class="card-header">
        <h3 class="float-left"> ArticleCategories list</h3>
        
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form  method="post">
                    <div  class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" />
                                <input type="text" name="Title" id="Title" value="" class="form-control" />
                           
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit"  value="create" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="index" asp-area="admin">Backto list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Edit.cshtml
@page "{id:long}"
@model MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement.EditModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left"> Edit ArticleCategory : @Model.ArticleCategory.Title</h3>
        
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div class="text-danger"></div>
                    <input type="hidden" asp-for="ArticleCategory.Id" />
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="ArticelCategory.Title" />
                            <input  asp-for="ArticleCategory.Title"   class="form-control" />

                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="index" asp-area="admin">Backto list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/ArticleCategoryManagement/Index.cshtml
@page
@model MB.Presentation.MVCCore2.Areas.Admin.Pages.ArticleCategoryManagement.IndexModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left"> ArticleCategories list</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./create" asp-area="admin">Create New</a>

        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Is Deleted</th>
                    <th>Created</th>
                    <th>Opreation</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var article in Model.ArtileCategories)
                {
                <tr>
                    <td>@article.Id</td>
                    <td>@article.Title</td>
                    <td>
                        @if (article.IsDeleted)
                        {
                            <i class="fa fa-close fa-2x text-danger"></i>
                        }
                        else
                        {
                            <i class="fa fa-check fa-2x text-success"></i>
                        }
                    </td>
                    <td>@article.Creation</td>
                    <td>
                        <a class="btn badge-warning  float-left mr-3" asp-page="./Edit" asp-route-id="@article.Id">Edit</a>
                        @if (article.IsDeleted)
                        {
                            <form method="post" asp-page-handler="Active" class="float-left">
                                <button class="badge-success ">Active</button>
                                <input type="hidden" name="id" value="@article.Id" />
                            </form>
                        }
                        else
                        {
                            <form method="post" asp-page-handler="Remove" class="float-left">
                                <button class="badge-danger ">Remove</button>
                                <input type="hidden" name="id" value="@article.Id" />
                            </form>
                        }
                    </td>
                </tr>   
                        }

                   
                </tbody>
        </table>
    </div>
</div>

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to AdminPage</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Areas/Admin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MB.Presentation.MVCCore2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MB.Presentation.MVCCore2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-page="/ArticleCategoryManagement/index">CategoryManagement</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MB.Presentation.MVCCore2 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Desktop/New folder/MasterBlogger/MasterBlogger/MB.Presentation.MVCCore2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}



<!-- post -->
<div class="post col-xl-6">
    <div class="post-thumbnail"><a href="post.html"><img src="~/img/blog-post-1.jpeg" alt="..." class="img-fluid"></a></div>
    <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">20 May | 2016</div>
            <div class="category"><a href="#">Business</a></div>
        </div><a href="post.html">
            <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3>
        </a>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <footer class="post-footer d-flex align-items-center">
            <a href="#" class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="img/avatar-3.jpg" alt="..." class="img-fluid"></div>
                <div class="title"><span>John Doe</span></div>
            </a>
            <div class="date"><i class="icon-clock"></i> 2 months ago</div>
            <div class="comments meta-last"><i class="icon-comment"></i>12</div>
        </footer>
    </div>
</div>
<!-- post             -->
<div class="post col-xl-6">
    <div class="post-thumbnail"><a href="post.html"><img src="~/img/blog-post-2.jpg" alt="..." class="img-fluid"></a></div>
    <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">20 May | 2016</div>
            <div class="category"><a href="#">Business</a></div>
        </div><a href="post.html">
            <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3>
        </a>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="post-footer d-flex align-items-center">
            <a href="#" class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="img/avatar-2.jpg" alt="..." class="img-fluid"></div>
                <div class="title"><span>John Doe</span></div>
            </a>
            <div class="date"><i class="icon-clock"></i> 2 months ago</div>
            <div class="comments meta-last"><i class="icon-comment"></i>12</div>
        </div>
    </div>
</div>
<!-- post             -->
<div class="post col-xl-6">
    <div class="post-thumbnail"><a href="post.html"><img src="~/img/blog-post-3.jpeg" alt="..." class="img-fluid"></a></div>
    <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">20 May | 2016</div>
            <div class="category"><a href="#">Business</a></div>
        </div><a href="post.html">
            <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3>
        </a>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="post-footer d-flex align-items-center">
            <a href="#" class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="img/avatar-3.jpg" alt="..." class="img-fluid"></div>
                <div class="title"><span>John Doe</span></div>
            </a>
            <div class="date"><i class="icon-clock"></i> 2 months ago</div>
            <div class="comments meta-last"><i class="icon-comment"></i>12</div>
        </div>
    </div>
</div>
<!-- post -->
<div class="post col-xl-6">
    <div class="post-thumbnail"><a href="post.html"><img src="~/img/blog-post-4.jpeg" alt="..." class="img-fluid"></a></div>
    <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">20 May | 2016</div>
            <div class="category"><a href="#">Business</a></div>
        </div><a href="post.html">
            <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3>
        </a>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="post-footer d-flex align-items-center">
            <a href="#" class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="img/avatar-1.jpg" alt="..." class="img-fluid"></div>
                <div class="title"><span>John Doe</span></div>
            </a>
            <div class="date"><i class="icon-clock"></i> 2 months ago</div>
            <div class="comments meta-last"><i class="icon-comment"></i>12</div>
        </div>
    </div>
</div>